version: "3.7"
services:
  fastify-container-sql-server-db:
    container_name: fastify-container-sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    networks:
      - fastify-container-network
    environment:
		# create a .env file with just DB_PASSWORD in this directory
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
networks:
  fastify-container-network:
    driver: bridge

# username sa by default